### ISSUE TITLE
Page error (connect ECONNREFUSED 

### ISSUE THREAD

**Issue by fivedoor** [DavidAnson/check-pages#7] opened 2016-07-17 21:30 UTC
Hi there,

Apologies if I'm stumbling over something obvious which I haven’t figured out from my end but I keep encountering the following error when trying to run checDev with gulp
```

[21:58:19] Starting 'checkDev'...
Checked 1 page and 0 links, found 1 issue.
Summary of issues:
 http://localhost:3000
  Page error (connect ECONNREFUSED 127.0.0.1:3000): http://localhost:3000 (24ms)

[21:58:20] 'checkDev' errored after 1.24 s
[21:58:20] Error: 1 issue.
    at /Users/fivedoor/Documents/development/fivedoor-email-frame/node_modules/check-pages/checkPages.js:426:13
    at next (/Users/fivedoor/Documents/development/fivedoor-email-frame/node_modules/check-pages/checkPages.js:435:5)
    at Request._callback (/Users/fivedoor/Documents/development/fivedoor-email-frame/node_modules/check-pages/checkPages.js:314:9)
    at self.callback (/Users/fivedoor/Documents/development/fivedoor-email-frame/node_modules/check-pages/node_modules/request/request.js:200:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/Users/fivedoor/Documents/development/fivedoor-email-frame/node_modules/check-pages/node_modules/request/request.js:831:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

I gather from a little googling that it may be a proxy issues but I’m not sure how to resolve it and if it’s a check-pages issue or something else my end (though not had any other issue using localhost: 3000 with any other tasks in my chain. 

Any advice on what the issue is / what to try / a solution greatly appreciated

Running the following:
gulp": ^3.9.1
check-pages": ^0.10.0
MACOS 10.11.4

Using the same settings as the Usage example gulp task except with localhost:3000

Thanks

**Comment by DavidAnson** [comment] 2016-07-17 21:52
If you visit the following links with a web browser, do they both work?

* http://localhost:3000/
* http://127.0.0.1:3000/

If so, what about if you try with `curl` instead?

**Comment by fivedoor** [comment] 2016-07-17 22:52
Hi David,
Thanks for your reply. 
Yes both the following work (while I have browserSync initiated I see my index page on both):
http://localhost:3000/
http://127.0.0.1:3000/

By curl do you mean https://github.com/curl/curl?
This is new to me so will read up on the site, try to get an idea of what's required and report back.

thanks for your help

**Comment by DavidAnson** [comment] 2016-07-17 23:02
curl: https://en.wikipedia.org/wiki/CURL

It's a command-line way to make web requests. For example, `curl http://localhost:3000 -v` will make a request and show the outgoing/incoming HTTP headers.

**Comment by fivedoor** [comment] 2016-07-17 23:06
Updating to report that the result of 
`curl http://localhost:3000` 
is 
`curl: (7) Failed to connect to localhost port 3000: Connection refused`

Also `curl http://localhost:3000 -v` results in the more verbose: 
```
* Rebuilt URL to: http://localhost:3000/
*   Trying ::1...
* connect to ::1 port 3000 failed: Connection refused
*   Trying 127.0.0.1...
* connect to 127.0.0.1 port 3000 failed: Connection refused
* Failed to connect to localhost port 3000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 3000: Connection refused
```

**Comment by DavidAnson** [comment] 2016-07-17 23:08
Seems like something's weird, then. There may certainly be a bug in my code, but curl should definitely work here. :) You mentioned above that you use a proxy? curl lets you specify proxy info via the `--proxy` switch - if you use a proxy and add that, is it able to get to the site? (Though it would be unusual to need a proxy to reach localhost.)

**Comment by fivedoor** [comment] 2016-07-17 23:20
I only really mentioned the proxy as from my digging around on line that seemed to be a common issue related to ECONNREFUSED errors. 

To be honest I’m still a fairly novice user of gulp and all things command line so I wouldn’t confidently rule out something horribly obvious from my end. I will try a few more things and report back (in the morning (as it’s getting late here in the UK!))… hopefully with a bit more to go on. Thanks.

**Comment by fivedoor** [comment] 2016-07-18 15:44
Logging a few more things tried without success today- 

Checked  the ports availability with ` netstat -a`.  3000 is not by the looks of it already in use

Tried an clean npm cache with `npm cache clean` then retried checkDev with same results

`curl 0.0.0.0:3000`
results in: 
`curl: (52) Empty reply from server`

**Comment by DavidAnson** [comment] 2016-07-19 04:11
Hum. At this point, I'd suggest troubleshooting with curl - once that works, I'm optimistic that check-pages will as well. I wonder if BrowserSync is interfering here? Do things work okay without it? The fact that netstat says the port is not in use suggests that maybe there's some trickery in place that allows the browser to think it's visiting localhost:3000 but it's really doing something else, maybe? I don't have a Mac or BrowserSync, so I'm not familiar with any issues that might be specific to them. :(

**Comment by DavidAnson** [comment] 2016-07-19 04:13
Maybe this? https://github.com/BrowserSync/browser-sync/issues/799
(See linked issue as well)

**Comment by DavidAnson** [comment] 2016-07-19 04:16
Maybe also relevant? http://stackoverflow.com/questions/27755206/using-the-original-url-not-proxy-with-browser-sync

**Comment by fivedoor** [comment] 2016-07-20 13:08
Thanks for the suggestions David

I didn’t have a lot of luck troubleshooting browserSync based ono the suggestions on the linked pages (though tbh the scope of what is discussed re the IPv4 vs IPv6  addresses not something I have any prior experience/knowledge of so there may be more milage to be gained there than I have managed as yet). 

What I did try with some success was taking browserSync completely out of the equation, stripped down my gulp file and use gulp-connect to initiate a server instead. 

Using gulp-connect I no longer came up against the ECONNREFUSED error so that narrows it down at least. 

Even though gulp-connect will work I would much rather be using browserSync for its capabilities so I’m hoping I will still be able to solve the issue using BrowserSync… So perhaps worth posting a query with their issues forum?  


(On a side note) I ran check-pages using the default checkDev task on a test page it was picking up a bad link that was an unresolved symbol: 
`Bad link (404): http://localhost:8080/_UNSUBLINK__ (17ms)`
however my test link http://www.deadlink-test.com was not picked up as inaccessible content which seems odd.

Thanks

**Comment by DavidAnson** [comment] 2016-07-21 04:42
Thanks for opening that bug! I hope they're able to help. :)

Regarding the bad link issue you mentioned at the bottom, can you create a small page to reproduce the problem? Paste it into a new issue and I'll have a look!

**Comment by fivedoor** [comment] 2016-07-21 14:38
Ok great - will do. thanks!

**Comment by DavidAnson** [comment] 2016-09-27 16:14
Closing as this appears to be due to an external component because `curl` has the same behavior. If you find a scenario where `curl` works and `check-pages` does not' please let me know the details! Thanks.

**Closed by DavidAnson** 2016-09-27 16:14 UTC
Labels: question
